import './imagePropertiesDialog.js'
import './editorPreferencesDialog.js'
import './svgSourceDialog.js'
import './cmenuDialog.js'
import './cmenuLayersDialog.js'
import './globalDialogs.js'
import './seStatusDialog.js'
import './exportDialog.js'
